package com.projeto.app.models.gestao;

public enum Descricao {

SEG_LIMPEZA, SANEPAR, MAT_LIMPEZA, COPEL, MARKETING, CONT_PRAGA, HONORARIOS, ENTRETENIMENTO, COLETA_LIXO, INTERNET, MAT_EXPEDIENTE, MANUTENÇÃO, IMPOSTOS, LOCAÇÕES, SEGURO;
    
}