package com.projeto.app.models.gestao;

public enum TipoEnum {

    SEG_LIMPEZA, SANEPAR, MAT_LIMPEZA, MARKETING, CONT_PRAGA, HONORARIOS, ENTRETERIMENTO, COLETA_LIXO, INTERNET,
    MAT_EXPEDIENTE, MANUTENÇÃO, IMPOSTOS, LOCAÇÕES, SEGURO;

}